# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Treasure.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
import pyqtgraph as pg

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1341, 869)
        MainWindow.setMinimumSize(QtCore.QSize(1341, 869))
        MainWindow.setMaximumSize(QtCore.QSize(1341, 869))
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(52, 0, 16, 881))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(60, 30, 1281, 16))
        self.line_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(330, 40, 20, 831))
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(60, 70, 281, 16))
        self.line_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setObjectName("line_4")
        self.line_5 = QtWidgets.QFrame(self.centralwidget)
        self.line_5.setGeometry(QtCore.QRect(340, 593, 1001, 16))
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.line_6 = QtWidgets.QFrame(self.centralwidget)
        self.line_6.setGeometry(QtCore.QRect(340, 634, 1001, 16))
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.leftwidget = QtWidgets.QWidget(self.centralwidget)
        self.leftwidget.setGeometry(QtCore.QRect(0, 0, 61, 871))
        self.leftwidget.setObjectName("leftwidget")
        self.aStock = QtWidgets.QToolButton(self.leftwidget)
        self.aStock.setGeometry(QtCore.QRect(0, 180, 61, 51))
        self.aStock.setStyleSheet("border:none;")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon/stock.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.aStock.setIcon(icon)
        self.aStock.setIconSize(QtCore.QSize(70, 70))
        self.aStock.setObjectName("aStock")
        self.futures = QtWidgets.QToolButton(self.leftwidget)
        self.futures.setGeometry(QtCore.QRect(0, 350, 61, 51))
        self.futures.setStyleSheet("border:none;")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icon/futures.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.futures.setIcon(icon1)
        self.futures.setIconSize(QtCore.QSize(70, 70))
        self.futures.setObjectName("futures")
        self.news = QtWidgets.QToolButton(self.leftwidget)
        self.news.setGeometry(QtCore.QRect(0, 530, 61, 51))
        self.news.setStyleSheet("border:none;")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icon/news.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.news.setIcon(icon2)
        self.news.setIconSize(QtCore.QSize(50, 50))
        self.news.setObjectName("news")
        self.closeButton = QtWidgets.QToolButton(self.centralwidget)
        self.closeButton.setGeometry(QtCore.QRect(1306, 3, 31, 31))
        self.closeButton.setStyleSheet("border:none;")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icon/close_3.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.closeButton.setIcon(icon3)
        self.closeButton.setIconSize(QtCore.QSize(30, 30))
        self.closeButton.setObjectName("closeButton")
        self.minimizeButton = QtWidgets.QToolButton(self.centralwidget)
        self.minimizeButton.setGeometry(QtCore.QRect(1270, 3, 31, 31))
        self.minimizeButton.setStyleSheet("border:none;")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("icon/minimize_4.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.minimizeButton.setIcon(icon4)
        self.minimizeButton.setIconSize(QtCore.QSize(30, 30))
        self.minimizeButton.setObjectName("minimizeButton")
        self.searchContent = QtWidgets.QLineEdit(self.centralwidget)
        self.searchContent.setGeometry(QtCore.QRect(150, 50, 151, 20))
        self.searchContent.setObjectName("searchContent")
        self.searchButton = QtWidgets.QToolButton(self.centralwidget)
        self.searchButton.setGeometry(QtCore.QRect(310, 50, 21, 21))
        self.searchButton.setStyleSheet("border:none;")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("icon/search.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.searchButton.setIcon(icon5)
        self.searchButton.setObjectName("searchButton")
        self.plusButton = QtWidgets.QToolButton(self.centralwidget)
        self.plusButton.setGeometry(QtCore.QRect(1309, 606, 31, 31))
        self.plusButton.setStyleSheet("border:none;")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("icon/plus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.plusButton.setIcon(icon6)
        self.plusButton.setIconSize(QtCore.QSize(30, 30))
        self.plusButton.setObjectName("plusButton")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(340, 259, 1001, 341))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.kLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.kLayout.setContentsMargins(0, 0, 0, 0)
        self.kLayout.setObjectName("kLayout")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(340, 40, 1001, 221))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.divideLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.divideLayout.setContentsMargins(0, 0, 0, 0)
        self.divideLayout.setObjectName("divideLayout")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(76, 39, 51, 40))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.blankLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.blankLayout.setContentsMargins(0, 0, 0, 0)
        self.blankLayout.setObjectName("blankLayout")
        self.shButton = QtWidgets.QRadioButton(self.verticalLayoutWidget_3)
        self.shButton.setChecked(True)
        self.shButton.setObjectName("shButton")
        self.blankLayout.addWidget(self.shButton)
        self.szButton = QtWidgets.QRadioButton(self.verticalLayoutWidget_3)
        self.szButton.setObjectName("szButton")
        self.blankLayout.addWidget(self.szButton)
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(340, 640, 1001, 231))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.tradeLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.tradeLayout.setContentsMargins(0, 0, 0, 0)
        self.tradeLayout.setObjectName("tradeLayout")
        self.label_1 = QtWidgets.QLabel(self.centralwidget)
        self.label_1.setGeometry(QtCore.QRect(350, 610, 41, 21))
        self.label_1.setStyleSheet("font-size:20px")
        self.label_1.setTextFormat(QtCore.Qt.AutoText)
        self.label_1.setObjectName("label_1")
        self.price = QtWidgets.QLabel(self.centralwidget)
        self.price.setGeometry(QtCore.QRect(392, 610, 101, 21))
        self.price.setStyleSheet("font-size:15px")
        self.price.setText("")
        self.price.setObjectName("price")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(500, 610, 21, 21))
        self.label.setStyleSheet("font-size:20px")
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(620, 610, 21, 21))
        self.label_3.setStyleSheet("font-size:20px")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(734, 610, 21, 20))
        self.label_4.setStyleSheet("font-size:20px")
        self.label_4.setObjectName("label_4")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(850, 610, 21, 21))
        self.label_6.setStyleSheet("font-size:20px")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(970, 610, 21, 21))
        self.label_7.setStyleSheet("font-size:20px")
        self.label_7.setObjectName("label_7")
        self.highprice = QtWidgets.QLabel(self.centralwidget)
        self.highprice.setGeometry(QtCore.QRect(520, 610, 101, 21))
        self.highprice.setStyleSheet("font-size:15px")
        self.highprice.setText("")
        self.highprice.setObjectName("highprice")
        self.lowprice = QtWidgets.QLabel(self.centralwidget)
        self.lowprice.setGeometry(QtCore.QRect(640, 610, 91, 21))
        self.lowprice.setStyleSheet("font-size:15px")
        self.lowprice.setText("")
        self.lowprice.setObjectName("lowprice")
        self.openprice = QtWidgets.QLabel(self.centralwidget)
        self.openprice.setGeometry(QtCore.QRect(753, 610, 101, 21))
        self.openprice.setStyleSheet("font-size:15px")
        self.openprice.setText("")
        self.openprice.setObjectName("openprice")
        self.tradeprice = QtWidgets.QLabel(self.centralwidget)
        self.tradeprice.setGeometry(QtCore.QRect(870, 610, 91, 21))
        self.tradeprice.setStyleSheet("font-size:15px")
        self.tradeprice.setText("")
        self.tradeprice.setObjectName("tradeprice")
        self.amount = QtWidgets.QLabel(self.centralwidget)
        self.amount.setGeometry(QtCore.QRect(992, 610, 131, 21))
        self.amount.setStyleSheet("font-size:15px")
        self.amount.setText("")
        self.amount.setObjectName("amount")
        self.name = QtWidgets.QLabel(self.centralwidget)
        self.name.setGeometry(QtCore.QRect(1139, 610, 111, 21))
        self.name.setStyleSheet("font-size:20px")
        self.name.setText("")
        self.name.setObjectName("name")
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(60, 80, 281, 791))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.favoriteLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.favoriteLayout.setContentsMargins(0, 0, 0, 0)
        self.favoriteLayout.setObjectName("favoriteLayout")
        self.deleteButton = QtWidgets.QToolButton(self.centralwidget)
        self.deleteButton.setGeometry(QtCore.QRect(1270, 606, 31, 31))
        self.deleteButton.setStyleSheet("border:none;")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("icon/minimize_2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.deleteButton.setIcon(icon7)
        self.deleteButton.setIconSize(QtCore.QSize(30, 30))
        self.deleteButton.setObjectName("deleteButton")
        MainWindow.setCentralWidget(self.centralwidget)

        self.k_plt = pg.PlotWidget()
        self.kLayout.addWidget(self.k_plt)

        self.trade = pg.PlotWidget()
        self.tradeLayout.addWidget(self.trade)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.aStock.setText(_translate("MainWindow", "..."))
        self.futures.setText(_translate("MainWindow", "..."))
        self.news.setText(_translate("MainWindow", "..."))
        self.closeButton.setText(_translate("MainWindow", "..."))
        self.minimizeButton.setText(_translate("MainWindow", "..."))
        self.searchButton.setText(_translate("MainWindow", "..."))
        self.plusButton.setText(_translate("MainWindow", "..."))
        self.shButton.setText(_translate("MainWindow", "上证"))
        self.szButton.setText(_translate("MainWindow", "深证"))
        self.label_1.setText(_translate("MainWindow", "现价"))
        self.label.setText(_translate("MainWindow", "高"))
        self.label_3.setText(_translate("MainWindow", "低"))
        self.label_4.setText(_translate("MainWindow", "开"))
        self.label_6.setText(_translate("MainWindow", "量"))
        self.label_7.setText(_translate("MainWindow", "额"))
        self.deleteButton.setText(_translate("MainWindow", "..."))

